import './bootstrap';
import './component/navbar-user';
import './component/alert';
import './component/alert-logout';
import './pages/login-user';
import './pages/register-user';
import './pages/produk';
import './pages/edit-profile';
import './pages/my-profile';