@php
    $fallbackItems = collect([
        (object) ['nama' => 'Geprek Ori', 'harga' => 12000, 'gambar' => null, 'toko' => (object) ['nama_toko' => 'Warung Bu Sri']],
        (object) ['nama' => 'Es pisang hijau', 'harga' => 8000, 'gambar' => null, 'toko' => (object) ['nama_toko' => 'Warung Bu Sri']],
    ]);
    $items = $produk->isNotEmpty() ? $produk : $fallbackItems;
    $shippingCost = 10000;
    $subtotal = $items->sum('harga');
@endphp
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <title>Checkout - LokaMarket</title>
</head>
<body class="min-h-screen bg-[#fffaf5] font-poppins text-[#3f2a20]">
    <header class="border-b border-[#f0dfd1] bg-white">
        <div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:h-[70px] sm:px-8">
            <a href="{{ route('cust.landingPage') }}" class="flex items-center gap-2.5" aria-label="Kembali ke LokaMarket"><img src="{{ asset('storage/logo-lokamarket.png') }}" alt="LokaMarket" class="h-10 w-auto object-contain sm:h-11"></a>
            <a href="{{ route('cust.caraKerja') }}" class="text-[10px] font-medium text-[#6e5b51] transition hover:text-[#d94d0b] sm:text-[11px]">Butuh bantuan?</a>
        </div>
    </header>

    <main class="mx-auto max-w-6xl px-4 py-7 sm:px-8 sm:py-10">
        <nav aria-label="Progress checkout" class="mx-auto mb-7 flex max-w-[540px] items-center text-[9px] font-semibold sm:text-[10px]">
            <a href="{{ route('cust.keranjang') }}" class="flex items-center gap-2 whitespace-nowrap text-[#9c897d]"><span class="flex h-6 w-6 items-center justify-center rounded-full bg-[#f36a12] text-white"><i class="fa-solid fa-check text-[9px]"></i></span><span>Keranjang</span></a><span class="mx-3 h-px flex-1 bg-[#f3b27f] sm:mx-5"></span><div class="flex items-center gap-2 whitespace-nowrap text-[#3f2a20]"><span class="flex h-6 w-6 items-center justify-center rounded-full bg-[#f36a12] text-white">2</span><span>Checkout</span></div><span class="mx-3 h-px flex-1 bg-[#ead8ca] sm:mx-5"></span><div class="flex items-center gap-2 whitespace-nowrap text-[#9c897d]"><span class="flex h-6 w-6 items-center justify-center rounded-full border border-[#f0daca] bg-white">3</span><span>Pembayaran</span></div>
        </nav>

        <div class="mx-auto max-w-[470px]">
            <div class="mb-4"><h1 class="text-2xl font-extrabold tracking-tight text-[#3d281e] sm:text-3xl">Checkout</h1><p class="mt-1 text-[10px] text-[#806e64] sm:text-[11px]">Lengkapi detail pesananmu sebelum lanjut ke pembayaran.</p></div>
            <form action="{{ route('cust.invoice') }}" method="GET" class="rounded-2xl border border-[#f0dfd1] bg-white px-5 py-4 shadow-[0_12px_35px_rgba(92,48,20,0.04)] sm:px-6">
                <section class="border-b border-[#f3e8e0] pb-4"><div class="flex items-center justify-between"><h2 class="text-[11px] font-extrabold">Alamat Pengiriman</h2><a href="{{ route('cust.editProfile') }}" class="text-[9px] font-bold text-[#d94d0b]">Ubah</a></div><div class="mt-3 flex gap-3 text-[10px]"><i class="fa-solid fa-location-dot mt-0.5 text-[#e9520d]"></i><div class="min-w-0"><p class="font-bold text-[#493329]">{{ $user->username }} <span class="font-normal text-[#a18d82]">&middot; {{ $user->no_telp ?: 'Nomor belum diisi' }}</span></p><p class="mt-1 leading-4 text-[#806e64]">{{ $user->alamat ?: 'Alamat belum diisi. Silakan lengkapi profil sebelum memesan.' }}</p></div></div></section>
                <section class="border-b border-[#f3e8e0] py-4"><h2 class="text-[11px] font-extrabold">Ringkasan Produk</h2><div class="mt-3 space-y-3">@foreach ($items as $item)<div class="flex items-center gap-3">@if ($item->gambar)<img src="{{ asset('storage/' . $item->gambar) }}" alt="{{ $item->nama }}" class="h-11 w-11 shrink-0 rounded-lg object-cover">@else<div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-[#fff0df] text-[#e9520d]"><i class="fa-solid fa-basket-shopping text-sm"></i></div>@endif<div class="min-w-0 flex-1"><p class="truncate text-[10px] font-bold text-[#4b3429]">{{ $item->nama }}</p><p class="text-[9px] text-[#9c877c]">{{ $item->toko->nama_toko ?? 'Penjual lokal' }} &middot; 1 pcs</p></div><p class="text-[10px] font-extrabold text-[#c9470e]">Rp {{ number_format($item->harga, 0, ',', '.') }}</p></div>@endforeach</div><div class="mt-4 flex items-center gap-2 rounded-lg bg-[#fff8f1] px-3 py-2"><i class="fa-solid fa-pen text-[10px] text-[#da5a17]"></i><input name="catatan" type="text" placeholder="Tambahkan catatan untuk penjual (opsional)" class="min-w-0 flex-1 bg-transparent text-[9px] outline-none placeholder:text-[#a99487]"></div></section>
                <fieldset class="border-b border-[#f3e8e0] py-4"><legend class="text-[11px] font-extrabold">Metode Pengiriman</legend><label class="mt-3 flex cursor-pointer items-start gap-2 text-[10px]"><input type="radio" name="pengiriman" value="reguler" checked class="mt-0.5 accent-[#e9520d]"><span class="flex-1"><strong class="block">Reguler</strong><small class="text-[9px] text-[#9c877c]">Estimasi tiba 2-3 hari</small></span><strong>Rp 10.000</strong></label><label class="mt-3 flex cursor-pointer items-start gap-2 text-[10px]"><input type="radio" name="pengiriman" value="express" class="mt-0.5 accent-[#e9520d]"><span class="flex-1"><strong class="block">Express</strong><small class="text-[9px] text-[#9c877c]">Estimasi tiba besok</small></span><strong>Rp 20.000</strong></label></fieldset>
                <fieldset class="border-b border-[#f3e8e0] py-4"><legend class="text-[11px] font-extrabold">Metode Pembayaran</legend><label class="mt-3 flex cursor-pointer items-start gap-2 text-[10px]"><input type="radio" name="pembayaran" value="transfer" checked class="mt-0.5 accent-[#e9520d]"><span class="flex h-5 w-5 items-center justify-center rounded-md bg-[#fff1e7] text-[#e9520d]"><i class="fa-regular fa-credit-card text-[10px]"></i></span><span><strong class="block">Transfer Bank</strong><small class="text-[9px] text-[#9c877c]">BCA, BNI, Mandiri</small></span></label><label class="mt-3 flex cursor-pointer items-start gap-2 text-[10px]"><input type="radio" name="pembayaran" value="ewallet" class="mt-0.5 accent-[#e9520d]"><span class="flex h-5 w-5 items-center justify-center rounded-md bg-[#fff1e7] text-[#e9520d]"><i class="fa-solid fa-wallet text-[10px]"></i></span><span><strong class="block">E-Wallet</strong><small class="text-[9px] text-[#9c877c]">GoPay, OVO, Dana</small></span></label><label class="mt-3 flex cursor-pointer items-start gap-2 text-[10px]"><input type="radio" name="pembayaran" value="cod" class="mt-0.5 accent-[#e9520d]"><span class="flex h-5 w-5 items-center justify-center rounded-md bg-[#fff1e7] text-[#e9520d]"><i class="fa-solid fa-box text-[10px]"></i></span><span><strong class="block">Bayar di Tempat (COD)</strong><small class="text-[9px] text-[#9c877c]">Bayar saat barang tiba</small></span></label></fieldset>
                <section class="pt-4"><h2 class="text-[11px] font-extrabold">Ringkasan Belanja</h2><dl class="mt-2 space-y-1 text-[9px] text-[#78655b]"><div class="flex justify-between"><dt>Subtotal Produk</dt><dd>Rp {{ number_format($subtotal, 0, ',', '.') }}</dd></div><div class="flex justify-between"><dt>Ongkos Kirim</dt><dd>Rp {{ number_format($shippingCost, 0, ',', '.') }}</dd></div><div class="flex justify-between"><dt>Biaya Layanan</dt><dd>Rp 1.000</dd></div><div class="flex justify-between"><dt>Diskon Voucher</dt><dd>-Rp 0</dd></div></dl><div class="mt-3 flex items-center gap-2 rounded-lg bg-[#fff8f1] px-3 py-2"><i class="fa-solid fa-ticket text-[10px] text-[#da5a17]"></i><input name="voucher" type="text" placeholder="Masukkan kode voucher" class="min-w-0 flex-1 bg-transparent text-[9px] outline-none placeholder:text-[#a99487]"><button type="button" class="text-[9px] font-bold text-[#d34c10]">Pakai</button></div><div class="mt-3 flex items-center justify-between border-t border-[#f3e8e0] pt-3"><span class="text-[11px] font-extrabold">Total Pembayaran</span><strong class="text-sm font-extrabold text-[#d94d0b]">Rp {{ number_format($subtotal + $shippingCost + 1000, 0, ',', '.') }}</strong></div><button type="submit" class="mt-4 flex h-9 w-full items-center justify-center rounded-full bg-[#e9520d] text-[10px] font-bold text-white shadow-sm transition hover:bg-[#cf4609]">Buat Pesanan</button><p class="mt-2 text-center text-[8px] leading-3 text-[#a38e82]">Dengan membuat pesanan, kamu menyetujui<br><span class="font-bold text-[#d34c10]">Syarat & Ketentuan LokaMarket</span></p></section>
            </form>
        </div>
    </main>
</body>
</html>